[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/dsgames.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

# Forçar o uso do Java 21
[env]
JAVA_VERSION = "21"
